In [1]:
import pickle
import pandas as pd

In [5]:
with open("books.pkl", "rb") as file:
    books = pickle.loads(file.read())

In [8]:
x = pd.DataFrame().from_dict(books)

In [10]:
x.head()

,itemid,vendorid,available,code,drmid,instock,itemimage,listprice,mf_status,mfgpartno,...,brandname,sub_isbn_TP,miniseriesid,miniseriesname,sub_isbn_PB,sub_isbn_AB,sub_isbn_HC,sub_isbn_LP,listprice_PTS,price_PTS
0,58054,20160106626,True,9780062271174,1,1,[/covers/9780062271174/y404.jpg],3.99,4,EB,...,[Avon],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,24301,20160106626,True,9780373210312,NaN,1,[/hqna/covers/9780373210312/y404.jpg],9.99,4,TP,...,[Harlequin Teen],[9780373210312],[34966],[Past Midnight],NaN,NaN,NaN,NaN,NaN,NaN
2,58048,20160106626,True,9780062268181,1,1,[/covers/9780062268181/y404.jpg],11.99,4,EB,...,[Avon],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,297314,20160106626,True,9781488053733,1,1,[/hqna/covers/9781488053733/y404.jpg],3.99,4,EB,...,[Carina Press],NaN,[54909],[Plot Twist],[9781335215741],[9781488206306],NaN,NaN,NaN,NaN
4,299057,20160106626,True,9781488053894,1,1,[/hqna/covers/9781488053894/y404.jpg],3.99,4,EB,...,[Carina Press],NaN,[54909],[Plot Twist],[9781335215857],[9781488206290],NaN,NaN,NaN,NaN

In [13]:
type(x["itemimage"].iloc[0])

list

In [14]:
x[x["itemimage"].apply(len) > 1]

Empty DataFrame
Columns: [itemid, vendorid, available, code, drmid, instock, itemimage, listprice, mf_status, mfgpartno, podate, price, publicationdate, shortdesc, soldout, title, width, authorid, authorname, productseourl, sub_format_exist_PB, sub_format_exist_EB, sub_isbn_EB, sub_digitalexcerpt_EB, sub_format_exist_HC, sub_format_exist_TP, sub_format_exist_LP, sub_format_exist_AB, listprice_USD, price_USD, listprice_CAD, price_CAD, categoryid, categoryname, brandid, brandname, sub_isbn_TP, miniseriesid, miniseriesname, sub_isbn_PB, sub_isbn_AB, sub_isbn_HC, sub_isbn_LP, listprice_PTS, price_PTS]
Index: []

[0 rows x 45 columns]